version: '3'

services:
  mini-drive:
    build: .
    ports:
      - 8080:8080
    environment:
      - spring.datasource.url=jdbc:mysql://database-1.czqc1c3mvi9q.ap-southeast-1.rds.amazonaws.com:3306/mini_drive
      - spring.datasource.username=admin
      - spring.datasource.password=Phuong0964603264
    volumes: 
      - storage:/storage

volumes:
  storage: